plugins:
  - jekyll-paginate
excerpt_separator: ""
highlighter: true
markdown: kramdown
theme: jekyll-theme-midnight
url: https://bioinformatics.age.mpg.de/blog
title: Bioinformatics blog
email: aiqbal@age.mpg.de
author: Ayesha Iqbal
description: Some useful notes and templates 
paginate: 4
google_analytics: 
