plugins:
  - jekyll-paginate
excerpt_separator: ""
highlighter: true
markdown: kramdown
url: https://bioinformatics.age.mpg.de/blog
title: Bioinformatics blog
email: bioinformatics@age.mpg.de
author: Bioinformatics Core Facility of the Max Planck Institute for Biology of Ageing
description: This is where we throw some code snippets and discuss stuff from time to time.
paginate: 4
google_analytics: 
